services:
  dev:
    build:
      context: .
      dockerfile: docker/old.Dockerfile
      target: development
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8888:8888"  # Jupyter
      - "8000:8000"  # FastAPI/Uvicorn
      - "6006:6006"  # TensorBoard
      - "5000:5000"  # MLflow
    stdin_open: true
    tty: true
